#!/bin/sh

set -e

# Perform all actions as $POSTGRES_USER
export PGUSER="$POSTGRES_USER"

env

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    

    CREATE SCHEMA $KEYCLOAK_DB_SCHEMA;
    CREATE USER $KEYCLOAK_DB_USER WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PWD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $KEYCLOAK_DB_USER;
    GRANT USAGE ON SCHEMA $KEYCLOAK_DB_SCHEMA TO $KEYCLOAK_DB_USER;
    GRANT CREATE ON SCHEMA $KEYCLOAK_DB_SCHEMA TO $KEYCLOAK_DB_USER;
    ALTER ROLE $KEYCLOAK_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $KEYCLOAK_DB_SCHEMA;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $KEYCLOAK_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $KEYCLOAK_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $KEYCLOAK_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $KEYCLOAK_DB_USER;

    CREATE SCHEMA $MICADO_DB_SCHEMA;
    CREATE USER $MICADO_DB_USER WITH ENCRYPTED PASSWORD '$MICADO_DB_PWD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $MICADO_DB_USER;
    GRANT USAGE ON SCHEMA $MICADO_DB_SCHEMA TO $MICADO_DB_USER;
    GRANT CREATE ON SCHEMA $MICADO_DB_SCHEMA TO $MICADO_DB_USER;
    ALTER ROLE $MICADO_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $MICADO_DB_SCHEMA;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $MICADO_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $MICADO_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $MICADO_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $MICADO_DB_USER;

    CREATE SCHEMA $GITEA_DB_SCHEMA;
    CREATE USER $GITEA_DB_USER WITH ENCRYPTED PASSWORD '$GITEA_DB_PWD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $GITEA_DB_USER;
    GRANT USAGE ON SCHEMA $GITEA_DB_SCHEMA TO $GITEA_DB_USER;
    GRANT CREATE ON SCHEMA $GITEA_DB_SCHEMA TO $GITEA_DB_USER;
    ALTER ROLE $GITEA_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $GITEA_DB_SCHEMA;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $GITEA_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $GITEA_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $GITEA_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $GITEA_DB_USER;

    CREATE SCHEMA $WEBLATE_DB_SCHEMA;
    CREATE USER $WEBLATE_POSTGRES_USER WITH ENCRYPTED PASSWORD '$WEBLATE_POSTGRES_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $WEBLATE_POSTGRES_USER;
    GRANT USAGE ON SCHEMA $WEBLATE_DB_SCHEMA TO $WEBLATE_POSTGRES_USER;
    GRANT CREATE ON SCHEMA $WEBLATE_DB_SCHEMA TO $WEBLATE_POSTGRES_USER;
    ALTER ROLE $WEBLATE_POSTGRES_USER IN DATABASE $POSTGRES_DB SET search_path = $WEBLATE_DB_SCHEMA;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $WEBLATE_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $WEBLATE_POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $WEBLATE_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $WEBLATE_POSTGRES_USER;

    CREATE EXTENSION IF NOT EXISTS pgroonga schema $MICADO_DB_SCHEMA;
    CREATE EXTENSION IF NOT EXISTS pgcrypto schema $MICADO_DB_SCHEMA;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp" schema $MICADO_DB_SCHEMA;
    CREATE EXTENSION IF NOT EXISTS pg_trgm  WITH SCHEMA $WEBLATE_DB_SCHEMA;
    CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA $WEBLATE_DB_SCHEMA;

    GRANT CREATE ON DATABASE $POSTGRES_DB TO $MICADO_DB_USER;
EOSQL

#     GRANT CREATE ON DATABASE $POSTGRES_DB TO $WEBLATE_POSTGRES_USER;

# ----- NEED TO CREATE BEFORE API SCHEMA SINCE MICADO WILL DEPEND ON SOME TABLES AND THUS THOSE TABLES NEED TO BE THERE OR REFERENCE WILL NOT WORK
# echo "\nCreating KEYCLOAK components\n"
# psql -c "CREATE USER $KEYCLOAK_DB_USER WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PWD';"
# psql -c "CREATE SCHEMA $KEYCLOAK_DB_SCHEMA;"
# psql -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $KEYCLOAK_DB_USER;"
# psql -c "GRANT USAGE ON SCHEMA $KEYCLOAK_DB_SCHEMA TO $KEYCLOAK_DB_USER;"
# psql -c "GRANT CREATE ON SCHEMA $KEYCLOAK_DB_SCHEMA TO $KEYCLOAK_DB_USER;"
# psql -c "ALTER ROLE $KEYCLOAK_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $KEYCLOAK_DB_SCHEMA;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $KEYCLOAK_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $KEYCLOAK_DB_USER;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $KEYCLOAK_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $KEYCLOAK_DB_USER;"

# echo "\nCreated KEYCLOAK components, now adding tables\n"


# echo "\nCreating GITEA components\n"
# psql -c "CREATE USER $GITEA_DB_USER WITH ENCRYPTED PASSWORD '$GITEA_DB_PWD';"
# psql -c "CREATE SCHEMA $GITEA_DB_SCHEMA;"
# psql -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $GITEA_DB_USER;"
# psql -c "GRANT USAGE ON SCHEMA $GITEA_DB_SCHEMA TO $GITEA_DB_USER;"
# psql -c "GRANT CREATE ON SCHEMA $GITEA_DB_SCHEMA TO $GITEA_DB_USER;"
# psql -c "ALTER ROLE $GITEA_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $GITEA_DB_SCHEMA;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $GITEA_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $GITEA_DB_USER;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $GITEA_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $GITEA_DB_USER;"

# echo "\nCreated GITEA components, now adding tables\n"


# echo "\nCreating MICADO apps components\n"
# psql -c "CREATE USER $MICADO_DB_USER WITH ENCRYPTED PASSWORD '$MICADO_DB_PWD';"
# psql -c "CREATE SCHEMA $MICADO_DB_SCHEMA;"
# psql -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $MICADO_DB_USER;"
# psql -c "GRANT USAGE ON SCHEMA $MICADO_DB_SCHEMA TO $MICADO_DB_USER;"
# psql -c "GRANT CREATE ON SCHEMA $MICADO_DB_SCHEMA TO $MICADO_DB_USER;"
# psql -c "ALTER ROLE $MICADO_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $MICADO_DB_SCHEMA;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $MICADO_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $MICADO_DB_USER;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $MICADO_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $MICADO_DB_USER;"

# # NOW GRANTING USAGE TO SCHEMA AND SPECIFIC TABLES
# psql -c "create extension \"uuid-ossp\" schema $MICADO_DB_SCHEMA"
# psql -c "create extension \"pgcrypto\" schema $MICADO_DB_SCHEMA"
# psql -c "create extension \"pgroonga\" schema $MICADO_DB_SCHEMA"


# # THIS IS TEMPORARY UNTILL LOOPBACK GET OUR PATCH
# psql -c "GRANT CREATE ON DATABASE $POSTGRES_DB TO $MICADO_DB_USER;"

# echo "\nCreated MICADO apps components, now adding tables\n"

# #psql -U $MICADO_DB_USER -d $POSTGRES_DB -a -q -f /docker-entrypoint-initdb.d/01_db.sql.txt

# #UNCOMMENT THIS IF YOU WANT TO HAVE THE DB WITH THE TABLES 
# psql -U $MICADO_DB_USER -d $POSTGRES_DB -a -q -f /docker-entrypoint-initdb.d/Micado_DB_Schema.sql.txt

# #CREATE indexes for full text searches for PGROONGA


# echo "\nCreating WEBLATE components\n"
# psql -c "CREATE USER $WEBLATE_POSTGRES_USER WITH ENCRYPTED PASSWORD '$WEBLATE_POSTGRES_PASSWORD';"
# psql -c "CREATE SCHEMA $WEBLATE_DB_SCHEMA;"
# psql -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $WEBLATE_POSTGRES_USER;"
# psql -c "GRANT USAGE ON SCHEMA $WEBLATE_DB_SCHEMA TO $WEBLATE_POSTGRES_USER;"
# psql -c "GRANT CREATE ON SCHEMA $WEBLATE_DB_SCHEMA TO $WEBLATE_POSTGRES_USER;"
# psql -c "ALTER ROLE $WEBLATE_POSTGRES_USER IN DATABASE $POSTGRES_DB SET search_path = $WEBLATE_DB_SCHEMA;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $WEBLATE_DB_SCHEMA GRANT ALL ON TABLES TO $WEBLATE_POSTGRES_USER;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $WEBLATE_DB_SCHEMA GRANT USAGE ON SEQUENCES TO $WEBLATE_POSTGRES_USER;"
# psql -c "CREATE EXTENSION IF NOT EXISTS pg_trgm  WITH SCHEMA $WEBLATE_DB_SCHEMA;"

# echo "\nCreated WEBLATE components, now adding tables\n"

# # ---------- RASA DB

# echo "\nCreating RASA components\n"
# psql -c "CREATE USER $RASA_DB_USER WITH ENCRYPTED PASSWORD '$RASA_DB_PASSWORD';"
# psql -c "CREATE SCHEMA $RASA_SCHEMA;"
# psql -c "GRANT CONNECT ON DATABASE $POSTGRES_DB TO $RASA_DB_USER;"
# psql -c "GRANT USAGE ON SCHEMA $RASA_SCHEMA TO $RASA_DB_USER;"
# psql -c "GRANT CREATE ON SCHEMA $RASA_SCHEMA TO $RASA_DB_USER;"
# psql -c "ALTER ROLE $RASA_DB_USER IN DATABASE $POSTGRES_DB SET search_path = $RASA_SCHEMA;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $RASA_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $RASA_DB_USER;"
# psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA $RASA_SCHEMA GRANT USAGE ON SEQUENCES TO $RASA_DB_USER;"

# echo "\nCreated RASA components, now adding tables\n"
